pluginGroup=com.dz.intellijjsonnet
pluginName=intellij-jsonnet-tanka
pluginVersion=0.1.0

pluginSinceBuild=242
platformType=IC
platformVersion=2024.2

org.gradle.configuration-cache=false
kotlin.stdlib.default.dependency=false
org.gradle.java.home=/Users/denis/Library/Java/JavaVirtualMachines/azul-21.0.10/Contents/Home
